name: 🧹 Faxina Pesada e Deploy Hostinger

on:
  push:
    branches:
      - main

jobs:
  clean-and-deploy:
    name: 🪠 Deletando Entulho e Subindo HTML Puro
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Puxando os arquivos limpos
      uses: actions/checkout@v4
    
    - name: 🗑️ Limpando a Hostinger e Sincronizando
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./
        server-dir: /public_html/salomaoquiz/
        clean: true
        clean-exclude: |
          .htaccess
